name: iccobs 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - pip
  - matplotlib=2.2.3
  - numpy=1.16.1
  - netCDF4=1.4.2
  - pandas=0.24.1
  - scipy=1.2.0
  - xarray=0.11.3
  - wxpython=4.0.3
  - dask=0.15.2
  - cartopy=0.17
  - metpy=0.10.0
  - pip:
    - pykrige==1.4.1
    - gooey==1.0.2
